version: "3.8"

services:
  redis:
    env_file: .env
    image: redis:6.0.9-alpine
    restart: always
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    mem_limit: 500M
    mem_reservation: 100m
    cpus: 0.3

  db:
    env_file: .env
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - klara-db-data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PORT}"
    mem_limit: 500M
    mem_reservation: 100m
    cpus: 0.3
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40
    logging:
      options:
        max-size: "100m"
        max-file: "1"

volumes:
  klara-db-data:
    name: klara-db-data
    external: true
