version: "3"

services:
  redis:
    image: redis:6.0.9-alpine
    restart: always
    logging:
      options:
        max-size: "100m"
        max-file: "3"

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - klara-db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "100m"
        max-file: "3"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: bash -c "python -m bot"
    env_file: .env
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  klara-db-data:
    name: klara-db-data
    external: true
