name: Publish to Registry

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: montenegroit/klara
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}
        registry: ghcr.io

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker down, pull and up remote host
      uses: appleboy/ssh-action@master
      env:
        ENVIRONMENT: development
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose down
          docker-compose pull
          docker-compose up -d