name: Publish to Registry

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker down and up on remote host
        uses: appleboy/ssh-action@master
        env:
          ENVIRONMENT: development
        with:
          host: ${{ secrets.KLARA_HOST }}
          username: ${{ secrets.KLARA_USER }}
          password: ${{ secrets.KLARA_PASSWORD }}
          script: |
            ls -al
            cd ${{ secrets.KLARA_PATH }}
            ls -al
            docker-compose -f server.yml down
            docker-compose -f server.yml up --build -d
