name: linter
on: [pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Isort check
        run: |
          isort bot --check-only --profile black
      - name: Black check
        run: |
          black --check bot
